// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmanCommunityServicesPlatform;

#nullable disable

namespace OmanCommunityServicesPlatform.Migrations
{
    [DbContext(typeof(OCSPContext))]
    [Migration("20260720095307_add-attachmentFileType")]
    partial class addattachmentFileType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Attachment", b =>
                {
                    b.Property<int>("attachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("attachmentId"));

                    b.Property<int>("fileType")
                        .HasColumnType("int");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("issueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("uploadedById")
                        .HasColumnType("int");

                    b.HasKey("attachmentId");

                    b.HasIndex("uploadedById");

                    b.HasIndex("issueId", "fileUrl")
                        .IsUnique();

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("categoryId");

                    b.HasIndex("categoryName")
                        .IsUnique();

                    b.HasIndex("departmentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"));

                    b.Property<DateTime>("commentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("isStaffComment")
                        .HasColumnType("bit");

                    b.Property<int>("issueId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("commentId");

                    b.HasIndex("issueId");

                    b.HasIndex("userId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<string>("contactEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("regionId")
                        .HasColumnType("int");

                    b.HasKey("departmentId");

                    b.HasIndex("departmentName")
                        .IsUnique();

                    b.HasIndex("regionId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Issue", b =>
                {
                    b.Property<int>("issueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("issueId"));

                    b.Property<int?>("assignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<int>("currentStatus")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.Property<int>("regionId")
                        .HasColumnType("int");

                    b.Property<int>("reportedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("reportedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("issueId");

                    b.HasIndex("assignedDepartmentId");

                    b.HasIndex("categoryId");

                    b.HasIndex("regionId");

                    b.HasIndex("reportedById");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Notification", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notificationId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<int?>("issueId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("type")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.HasIndex("issueId");

                    b.HasIndex("userId", "issueId", "type", "message")
                        .IsUnique()
                        .HasFilter("[issueId] IS NOT NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Rating", b =>
                {
                    b.Property<int>("ratingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ratingId"));

                    b.Property<string>("feedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("issueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ratingId");

                    b.HasIndex("userId");

                    b.HasIndex("issueId", "userId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Region", b =>
                {
                    b.Property<int>("regionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("regionId"));

                    b.Property<int>("governorate")
                        .HasColumnType("int");

                    b.Property<string>("regionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("regionId");

                    b.HasIndex("regionName")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.StatusUpdate", b =>
                {
                    b.Property<int>("statusUpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusUpdateId"));

                    b.Property<int>("issueId")
                        .HasColumnType("int");

                    b.Property<int>("newStatus")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("previousStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("updatedById")
                        .HasColumnType("int");

                    b.HasKey("statusUpdateId");

                    b.HasIndex("issueId");

                    b.HasIndex("updatedById");

                    b.ToTable("StatusUpdates");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int?>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("regionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("departmentId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("regionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Attachment", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Issue", "issue")
                        .WithMany("attachments")
                        .HasForeignKey("issueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmanCommunityServicesPlatform.Models.User", "uploadedBy")
                        .WithMany("Attachments")
                        .HasForeignKey("uploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("issue");

                    b.Navigation("uploadedBy");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Category", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Department", "department")
                        .WithMany("Categories")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Comment", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Issue", "issue")
                        .WithMany("comments")
                        .HasForeignKey("issueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmanCommunityServicesPlatform.Models.User", "user")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("issue");

                    b.Navigation("user");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Department", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Region", "region")
                        .WithMany("Departments")
                        .HasForeignKey("regionId");

                    b.Navigation("region");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Issue", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Department", "assignedDepartment")
                        .WithMany("Issues")
                        .HasForeignKey("assignedDepartmentId");

                    b.HasOne("OmanCommunityServicesPlatform.Models.Category", "category")
                        .WithMany("Issues")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmanCommunityServicesPlatform.Models.Region", "region")
                        .WithMany("Issues")
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmanCommunityServicesPlatform.Models.User", "reportedBy")
                        .WithMany("Issues")
                        .HasForeignKey("reportedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assignedDepartment");

                    b.Navigation("category");

                    b.Navigation("region");

                    b.Navigation("reportedBy");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Notification", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Issue", "issue")
                        .WithMany("notifications")
                        .HasForeignKey("issueId");

                    b.HasOne("OmanCommunityServicesPlatform.Models.User", "user")
                        .WithMany("Notifications")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("issue");

                    b.Navigation("user");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Rating", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Issue", "Issue")
                        .WithMany("ratings")
                        .HasForeignKey("issueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmanCommunityServicesPlatform.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.StatusUpdate", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Issue", "issue")
                        .WithMany("statusUpdates")
                        .HasForeignKey("issueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmanCommunityServicesPlatform.Models.User", "updatedBy")
                        .WithMany("StatusUpdates")
                        .HasForeignKey("updatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("issue");

                    b.Navigation("updatedBy");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.User", b =>
                {
                    b.HasOne("OmanCommunityServicesPlatform.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("departmentId");

                    b.HasOne("OmanCommunityServicesPlatform.Models.Region", "Region")
                        .WithMany("Users")
                        .HasForeignKey("regionId");

                    b.Navigation("Department");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Category", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Department", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Issues");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Issue", b =>
                {
                    b.Navigation("attachments");

                    b.Navigation("comments");

                    b.Navigation("notifications");

                    b.Navigation("ratings");

                    b.Navigation("statusUpdates");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.Region", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Issues");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OmanCommunityServicesPlatform.Models.User", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Issues");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("StatusUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
