/** Backend routes used by the frontend. Preserve the backend route casing. */
export const endpoints = Object.freeze({
  login: "/user/login",
  register: "/user/register",
  myIssues: "/issue/GetMyIssues",
  allIssues: "/issue/GetAllIssues",
  issueById: (issueId: number) => `/issue/GetIssueById/${issueId}`,
  createIssue: "/issue/Create",
  changeIssueStatus: (issueId: number) => `/issue/ChangeIssueStatus/${issueId}`,
  allStatusUpdates: "/api/StatusUpdate",
  statusUpdatesByIssue: (issueId: number) => `/api/StatusUpdate/issue/${issueId}`,
  categories: "/category/GetAllCategories",
  createCategory: "/category/Add",
  regions: "/region/GetAll",
  createRegion: "/region/Add",
  departments: "/department/GetAllDepartments",
  createDepartment: "/department/Add",
  commentsByIssue: (issueId: number) => `/comment/issue/${issueId}`,
  createComment: "/comment/newComment",
  attachmentsByIssue: (issueId: number) => `/attachment/Issue/${issueId}`,
  createAttachment: "/attachment/Create",
  updateAttachment: (attachmentId: number) => `/attachment/Update/${attachmentId}`,
  ratingsByIssue: (issueId: number) => `/rating/GetByIssueId/${issueId}`,
  createRating: "/rating/Create",
  updateRating: (ratingId: number) => `/rating/Update/${ratingId}`,
  myNotifications: "/notification/my",
  unreadNotifications: "/notification/my/unread",
  markNotificationRead: (notificationId: number) => `/notification/${notificationId}/read`
});
